apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationlistener
  namespace: notification
  labels:
    app: notificationlistener
spec:
  replicas: 5
  selector:
    matchLabels:
      app: notificationlistener
  template:
    metadata:
      labels:
        app: notificationlistener
    spec:
      containers:
      - name: notificationlistener
        image: 811095632387.dkr.ecr.us-east-2.amazonaws.com/notificationlistener:main
        ports:
        - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: notification
  name: notificationlistener
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationlistener
  minReplicas: 5
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  namespace: notification
  name: notificationlistener
spec:
  type: NodePort
  selector:
    app: notificationlistener
  ports:
    - name: notificationlistener
      port: 8080
      targetPort: 8080
