apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationapi
  namespace: notification
  labels:
    app: notificationapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationapi
  template:
    metadata:
      labels:
        app: notificationapi
    spec:
      containers:
      - name: notificationapi
        image: 811095632387.dkr.ecr.us-east-2.amazonaws.com/notificationapi:main
        ports:
        - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notificationapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationapi
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  namespace: notification
  name: notificationapi
spec:
  type: NodePort
  selector:
    app: notificationapi
  ports:
    - name: notificationapi
      port: 8080
      targetPort: 8080
