apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationbatch
  namespace: notification
  labels:
    app: notificationbatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notificationbatch
  template:
    metadata:
      labels:
        app: notificationbatch
    spec:
      containers:
      - name: notificationbatch
        image: 811095632387.dkr.ecr.us-east-2.amazonaws.com/notificationbatch:main
        ports:
        - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notificationbatch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notificationbatch
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  namespace: notification
  name: notificationbatch
spec:
  type: NodePort
  selector:
    app: notificationbatch
  ports:
    - name: notificationbatch
      port: 8080
      targetPort: 8080
